import React, {useState} from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ethers } from 'ethers'
// import  ContractJSON  from '../contract/abi/abi.json'
// import Addresses from '../contract/address/addresses'

declare let window: any;

export default function Home() {

  // const contractAddress = Addresses.address
  // const ContractABI = ContractJSON
  const [defaultAccount, setDefaultAccount] = useState('connect Wallet')
  const accountChangedHandler = (myAccount) => {
    setDefaultAccount(myAccount);
  }

  const ConnectMask = async (): Promise<boolean> => {
    try {
      await window.ethereum.request({ method: "eth_requestAccounts" }).then(result => {
        accountChangedHandler(result[0])
      })
    } catch (e: any){
        return false
    }
  }

  // const getCurrentValue = async (): Promise<number> => {
  //   const provider = new ethers.providers.JsonRpcProvider();
  //   let value = await provider.getBalance("ethers.eth")
  //   let valueNumber = Number(ethers.utils.formatEther(value))
  //   return valueNumber
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        {/* <p>{getCurrentValue}eth</p> */}
        <p>{defaultAccount}</p>
        <button onClick={ConnectMask}>connect</button>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
