import React, {useState} from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ethers } from 'ethers'
import ContractJSON from '../contract/abi/abi.json'
import Addresses from '../contract/address/addresses'

// 応急措置
declare let window: any;

export default function Home() {

  const contractAddress = Addresses.address
  const ContractABI = ContractJSON.abi

  // ローカル接続
  let network = 'http://localhost:8545'
  let provider = ethers.getDefaultProvider(network)

  const [defaultAccount, setDefaultAccount] = useState('connect Wallet')
  const [balance, setBalance] = useState(null)

  const accountChangedHandler = (myAccount:string) => {
    setDefaultAccount(myAccount);
  }

  const getCurrentValue = async (myAccount): Promise<void> => {
    let balance = await provider.getBalance(myAccount)
    let balanceNumber = ethers.utils.formatEther(balance)
    setBalance(balanceNumber)
  }

  const ConnectMask = async (): Promise<boolean> => {
    try {
      await window.ethereum.request({ method: "eth_requestAccounts" }).then(result => {
        // console.log(result[0])
        accountChangedHandler(result[0])
        getCurrentValue(result[0])
      })
    } catch (error: any) {
        console.log(error)
        return false
    }
  }

  const mintToken = async (): Promise<void> => {
    const provider = await new ethers.providers.Web3Provider(window.ethereum);
    await provider.send("eth_requestAccounts", []);
    const signer = provider.getSigner();
    console.log(signer._address)
    const contract = new ethers.Contract(contractAddress, ContractABI, signer)
    await contract.mint(signer,1)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <p>{balance}eth</p>
        <p>{defaultAccount}</p>
        <button onClick={ConnectMask}>connect</button>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button onClick={mintToken}>mint</button>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
